version: '3'
name: routenotfound
networks:
  rnf:
    name: route-not-found
    enable_ipv6: false
services:
  postgrest:
    image: postgrest/postgrest
    restart: "always"
    ports:
      - "3000:3000"
    networks:
      - rnf
    environment:
      PGRST_DB_URI: "postgres://${PG_USER}:${PG_PASSWD}@postgres:5432/rnf_location"
      PGRST_DB_ANON_ROLE: web_requests
      PGRST_DB_SCHEMAS: public
      PGRST_DB_CONFIG: 0
      PGRST_JWT_SECRET: ${PGRST_SECRET}
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - postgres
  postgres:
    build: ./postgres
    restart: "always"
    ports:
      - "5432:5432"
    networks:
      - rnf
    environment:
      POSTGRES_DB: rnf_location
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWD}
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
  mariadb:
    image: "mariadb:10"
    restart: "always"
    ports:
      - "3306:3306"
    networks:
      - rnf
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/logs:/var/log/mysql
      - ./mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MS_SUPER}
      MYSQL_DATABASE: rnf_content
      MYSQL_USER: ${MS_USER}
      MYSQL_PASSWORD: ${MS_PASSWD}
  apache:
    build: ./apache
    restart: "always"
    depends_on:
      - mariadb
    ports:
      - "80:80"
      - "443:443"
    networks:
      - rnf
    links:
      - mariadb
    volumes:
      - ./apache/docroot:/var/www/html
      - ./apache/logs:/var/log/www
    environment:
      MS_DB: rnf_content
      MS_USER: ${MS_USER}
      MS_PASSWD: ${MS_PASSWD}
      MS_HOST: routenotfound-mariadb-1
  cftunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel run --token ${CFD_TOKEN}
    networks:
      - rnf
